// <auto-generated />
namespace DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class init_basiceFileAdded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(init_basiceFileAdded));
        
        string IMigrationMetadata.Id
        {
            get { return "202401010704481_init_basiceFileAdded"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
